# Generated by Django 5.0.3 on 2024-03-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='contact',
        ),
    ]
